[workspace]
members = ["sys","examples"]

[package]
name = "whisper-rs"
version = "0.3.0"
edition = "2021"
description = "Rust bindings for whisper.cpp"
license = "Unlicense"
documentation = "https://docs.rs/whisper-rs"
repository = "https://github.com/tazz4843/whisper-rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
whisper-rs-sys = { path = "sys", version = "0.2" }
hound = "3.5.0"

[features]
simd = []

[package.metadata.docs.rs]
features = ["simd"]
