[workspace]
members = ["sys","examples"]

[package]
name = "whisper-rs"
version = "0.3.0"
edition = "2021"
description = "Rust bindings for whisper.cpp"
license = "Unlicense"
documentation = "https://docs.rs/whisper-rs"
repository = "https://github.com/m1guelpf/whisper-rs-bindings"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
whisper-rs-sys = { path = "sys", version = "0.2" }

[features]
simd = []

[dev-dependencies]
hound = "3.5.0"

[package.metadata.docs.rs]
features = ["simd"]
