[package]
name = "audio-transcription"
version = "0.1.0"
edition = "2021"
description = "Example usage of whisper-rs"
license = "Unlicense"

[dependencies]
whisper-rs = { path = ".." }
hound = "3.5.0"

[[bin]]
name = "audio-transcription"
path = "audio_transcription/main.rs"
